name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Run Bazel Tests
        run: bazel test //... --build_tests_only

      - name: Build and load service image
        run: bazel run //mpm:service_image_load

      - name: Upload to Artifact Registry
        run: echo "todo"
