name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # # # # # # # # # # # # # # # #
      # Setup GCP and. Follows:
      # http://github.com/google-github-actions/auth.git
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'my-repo'
          token_format: access_token
          workload_identity_provider: 'projects/29291984549/locations/global/workloadIdentityPools/github/providers/my-repo'
          service_account: 29291984549-compute@developer.gserviceaccount.com

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: northamerica-northeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # # # # # # # # # # # # # # # #
      # Build, test and upload image to artifact registry.
      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Run Bazel Tests and Build Image
        run: |
          bazel test //... --build_tests_only
          bazel run //mpm:service_image_load

      - name: Tag and push to Artifact Registry
        run: |
          IMAGE_NAME=northamerica-northeast1-docker.pkg.dev/dev-projects-455909/test/service
          docker tag service:latest ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:latest
