name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Run Bazel Tests
        run: bazel test //... --build_tests_only

      - name: Build and load service image
        run: bazel run //mpm:service_image_load

      # Follows http://github.com/google-github-actions/auth.git.
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'my-repo'
          workload_identity_provider: 'projects/29291984549/locations/global/workloadIdentityPools/github/providers/my-repo'

      - name: Upload to Artifact Registry
        run: |
          docker push northamerica-northeast1-docker.pkg.dev/dev-projects-455909/test/service:latest
